// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa4n9kdshjrnWGiQvJdshT3g3prT_zfLo',
    appId: '1:279474906769:web:185efa7ec781dca0798130',
    messagingSenderId: '279474906769',
    projectId: 'diary-app-course-67fbc',
    authDomain: 'diary-app-course-67fbc.firebaseapp.com',
    storageBucket: 'diary-app-course-67fbc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz5v1ql1LqiKkn-C3UwvbJ1XQ7YqzPY_U',
    appId: '1:279474906769:android:6a182de6de3fbf82798130',
    messagingSenderId: '279474906769',
    projectId: 'diary-app-course-67fbc',
    storageBucket: 'diary-app-course-67fbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEfcn9kuRh9bjri7S5h-VT1cleHuXJ54U',
    appId: '1:279474906769:ios:8001a800200d1953798130',
    messagingSenderId: '279474906769',
    projectId: 'diary-app-course-67fbc',
    storageBucket: 'diary-app-course-67fbc.appspot.com',
    iosClientId: '279474906769-p9qkoic6tm3camdcp9i0p7um884nfmmi.apps.googleusercontent.com',
    iosBundleId: 'com.example.diaryAndroidstudio',
  );
}
